const styles = {
  lightTheme: {
    backgroundColor: '#F9FAFB',
    textColor: '#333333',
    secondaryTextColor: '#666666',
    cardBackground: '#FFFFFF',
    chatAreaBackground: 'linear-gradient(135deg, #F9FAFB 0%, #E0F7FA 100%)',
    sidebarBackground: '#F1F5F9',
  },
  darkTheme: {
    backgroundColor: '#1F2A44',
    textColor: '#E0E0E0',
    secondaryTextColor: '#A0A0A0',
    cardBackground: '#2E3958',
    chatAreaBackground: 'linear-gradient(135deg, #1F2A44 0%, #2E3958 100%)',
    sidebarBackground: '#2A3550',
  },
  navbarLight: {
    background: 'linear-gradient(90deg, #7B1FA2 0%, #AB47BC 100%)',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    padding: '15px 20px',
  },
  navbarDark: {
    background: 'linear-gradient(90deg, #26A69A 0%, #4DB6AC 100%)',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    padding: '15px 20px',
  },
  navbarBrand: {
    color: '#FFFFFF',
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  themeSwitch: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: '#FFFFFF',
  },
  themeSwitchIcon: {
    transition: 'transform 0.3s ease',
  },
  sidebarHeaderLight: {
    background: 'linear-gradient(90deg, #FF6F61 0%, #FF8A80 100%)',
    color: '#FFFFFF',
    padding: '10px 15px',
    borderRadius: '8px',
    marginBottom: '15px',
    fontSize: '1.25rem',
    fontWeight: '600',
    textAlign: 'center',
  },
  sidebarHeaderDark: {
    background: 'linear-gradient(90deg, #26A69A 0%, #4DB6AC 100%)',
    color: '#FFFFFF',
    padding: '10px 15px',
    borderRadius: '8px',
    marginBottom: '15px',
    fontSize: '1.25rem',
    fontWeight: '600',
    textAlign: 'center',
  },
  sidebarItem: {
    marginBottom: '8px',
    borderRadius: '8px',
    padding: '12px',
    border: 'none',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
    cursor: 'pointer',
  },
  sidebarItemHover: {
    transform: 'scale(1.02)',
  },
  clearButton: {
    backgroundColor: '#FF7043',
    borderColor: '#FF7043',
    borderRadius: '8px',
    padding: '10px',
    fontWeight: '500',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
  },
  clearButtonHover: {
    backgroundColor: '#F4511E',
    borderColor: '#F4511E',
    transform: 'scale(1.05)',
  },
  messageCard: {
    width: '85%',
    marginBottom: '15px',
    borderRadius: '12px',
    border: 'none',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    transition: 'transform 0.2s ease, box-shadow 0.3s ease',
    animation: 'fadeIn 0.5s ease-in-out',
  },
  messageCardHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
  },
  userMessageBorder: {
    borderLeft: '4px solid #42A5F5',
  },
  assistantMessageBorder: {
    borderLeft: '4px solid #26A69A',
  },
  loadingCard: {
    width: '85%',
    marginBottom: '15px',
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    backgroundColor: '#FFF3E0',
    color: '#FF7043',
  },
  alertSuccess: {
    width: '85%',
    borderRadius: '8px',
    backgroundColor: '#E0F7FA',
    color: '#26A69A',
    borderColor: '#26A69A',
  },
  alertSuccessDark: {
    width: '85%',
    borderRadius: '8px',
    backgroundColor: '#00695C',
    color: '#E0E0E0',
    borderColor: '#4DB6AC',
  },
  alertDanger: {
    width: '85%',
    borderRadius: '8px',
    backgroundColor: '#FFEBEE',
    color: '#EF5350',
    borderColor: '#EF5350',
  },
  inputSection: {
    position: 'sticky',
    bottom: 0,
    padding: '15px',
    borderTop: '1px solid #dfe4ea',
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    boxShadow: '0 -2px 8px rgba(0, 0, 0, 0.05)',
    background: 'linear-gradient(90deg, #E0F7FA 0%, #F9FAFB 100%)',
  },
  inputSectionDark: {
    background: 'linear-gradient(90deg, #2E3958 0%, #1F2A44 100%)',
  },
  select: {
    width: '150px',
    borderRadius: '8px',
    border: '1px solid #26A69A',
    padding: '8px',
    backgroundColor: '#FFFFFF',
    transition: 'border-color 0.3s ease',
  },
  selectDark: {
    backgroundColor: '#3B486B',
    color: '#E0E0E0',
    borderColor: '#4DB6AC',
  },
  selectHover: {
    borderColor: '#FF7043',
  },
  input: {
    flex: 1,
    borderRadius: '8px',
    padding: '10px',
    border: '1px solid #26A69A',
    backgroundColor: '#FFFFFF',
    transition: 'border-color 0.3s ease',
  },
  inputDark: {
    backgroundColor: '#3B486B',
    color: '#E0E0E0',
    borderColor: '#4DB6AC',
  },
  inputHover: {
    borderColor: '#FF7043',
  },
  button: {
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    backgroundColor: '#26A69A',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
  },
  buttonHover: {
    backgroundColor: '#4DB6AC',
    transform: 'scale(1.1)',
  },
  buttonRecording: {
    backgroundColor: '#EF5350',
  },
  buttonRecordingHover: {
    backgroundColor: '#F44336',
    transform: 'scale(1.1)',
  },
};

export default styles;